baseURL: "https://amanpriyanshu.github.io/blogs/"
title: Decoding AI's Evolution
paginate: 10
theme: PaperMod
copyright: " "
publishDir: docs

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true


minify:
    disableXML: true



    
outputs:
    home:
        - HTML
        - RSS
        - JSON

menu:
    main:
      - name: My homepage
        url: "https://amanpriyanshu.github.io/"
        weight: 5     
      - name: Categories
        url: categories/
        weight: 10 
      - name: Tags
        url: tags/
        weight: 15   
      - name: My Personal Model Picks
        url: "https://amanpriyanshu.github.io/My-Personal-Model-Picks/"
        weight: 20               
      - name: Archive
        url: archives/
        weight: 25    
      - name: Search
        url: search/
        weight: 30




params:
    description: ""
    author: Aman Priyanshu

    defaultTheme: auto
    ShowShareButtons: true
    ShowReadingTime: true
    disableSpecial1stPost: true
    displayFullLangName: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowToc: true
    cover:
        responsiveImages: false
        hiddenInSingle: true 

    
    homeInfoParams:
        Title: Greetings, Programs!!
        Content: >
            Welcome to my digital arena where I want to explore the evolving world of AI with my special twists and turns. There'll be safety stuff, privacy stuff, and bio-inspirations that bridge the gap between silicon and synapse.

    socialIcons:
        - name: LinkedIn
          url: "https://www.linkedin.com/in/aman-priyanshu/"
        - name: Email
          url: "mailto:amanpriyanshusms2001@gmail.com"
        - name: github
          url: "https://github.com/AmanPriyanshu"  
        - name: twitter
          url: "https://twitter.com/AmanPriyanshu6"        

taxonomies:
    category: categories
    tag: tags
    series: series

markup:
     goldmark:
        renderer:
            unsafe: true

    